version: '3.9'
services:
  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    volumes:
      - ./waity.sql:/docker-entrypoint-initdb.d/waity.sql
    environment:
      - MYSQL_ROOT_PASSWORD=Woals0313!
      - MYSQL_DATABASE=yt

  app:
    image: pos05169/waity-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:log4jdbc:mysql://db:3306/yt?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Woals0313!
    depends_on:
      - db
    restart: always
