## mysql
spring:
  config.activate.on-profile: default
  datasource:
    hikari:
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbcUrl: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      connection-test-query: SELECT NOW() FROM dual

## mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true

## logger
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    rolling-file-name: "/logs/waity.%d{yyyy-MM-dd}.%i"
  file:
    name: /logs/waity.log
    max-history: 30
  level:
    com:
      waity: info
      zaxxer: off
    org:
      springframework: info
      apache: off
    jdbc:
      audit: off
      resultset: off
      resultsettable: off  #SQL 결과 데이터 Table을 로그로 남긴다.
      sqlonly: off     #SQL만 로그로 남긴다.
      sqltiming: info    #SQL과 소요시간을 표기한다.
      connection: off  # 커넥션 확인가능


## youtube
youtube:
  key: ${YOUTUBE_DATA_API_KEY}
  endpoint: ${YOUTUBE_DATA_API_ENDPOINT}

---

spring:
  config.activate.on-profile: test
  datasource:
    hikari:
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbcUrl: jdbc:log4jdbc:mysql://localhost:3306/yt?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Woals0313!
      connection-test-query: SELECT NOW() FROM dual

## mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true

## logger
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      springframework: INFO
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: info
      audit: off
      resultset: off
      connection: off

## youtube
youtube:
  key: AIzaSyBzXpb-djwWT18JGwQCWLS3Fg4B_ZVLFfQ
  endpoint: https://www.googleapis.com/youtube/v3